# Generated by Django 4.1.7 on 2024-01-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_websiteinfo_hero_image_alter_websiteinfo_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intership',
            fields=[
                ('custom_id', models.AutoField(primary_key=True, serialize=False)),
                ('Intership_Title', models.TextField()),
                ('company_name', models.TextField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('published_time', models.DateTimeField(auto_now=True)),
                ('photo_intership', models.ImageField(upload_to='static/img/intership_logo')),
                ('Categary_post', models.TextField(blank=True, default='fresher/experience', max_length=50, null=True)),
                ('Batch', models.CharField(blank=True, default='Any', max_length=40, null=True)),
                ('Location', models.TextField(default='Not Specify')),
                ('Last_day_apply', models.TextField(blank=True, default='Not Specify', null=True)),
                ('Requirments', models.TextField(blank=True, default='Bachelor’s degree in Computer Science or equivalent.Experience of Java and/or Javascript an advantage.Experience working within an Agile team an advantageFluent in English.High levels of curiosity and autonomy.Experience or knowledge of any of the following an advantage; SAP Lumira,.Experience or knowledge of any of the following an advantage; SAP Lumira, SAP Business Intelligence Platform, SAP BW, SAP HANA, SAP UI5.Preparation of unit tests.Communicate proactively, precisely & accurately.Interact with colleagues in a highly international environment.Demonstrated problem solving and solution building skills as well as the initiative to deliver results..Preparation of unit tests.You value teamwork and have excellent collaboration skills.', null=True)),
                ('streams', models.TextField(blank=True, default='All streams/branches of B.E/B.Tech/M.E/M.Tech, MCA, and M.Sc. (CSE, IT only)', null=True)),
                ('Salary', models.IntegerField(default='Not Specify')),
                ('Applly_link', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='websiteinfo',
            name='hero_image',
            field=models.ImageField(upload_to='static/img/'),
        ),
    ]
