# Generated by Django 4.1.7 on 2024-01-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_intership_alter_websiteinfo_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intership',
            name='Salary',
            field=models.CharField(default='Not Specify', max_length=20),
        ),
    ]
