# Generated by Django 4.1.7 on 2024-01-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_intership_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=255)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=255)),
                ('experience', models.CharField(blank=True, default='fresher/experience', max_length=50, null=True)),
                ('batch', models.CharField(blank=True, default='Any', max_length=50, null=True)),
                ('job_location', models.CharField(default='Not Specify', max_length=255)),
                ('last_day_to_apply', models.DateField(blank=True, default='__', null=True)),
                ('requirements', models.TextField(blank=True, default='Bachelor’s degree in Computer Science or equivalent.Experience of Java and/or Javascript an advantage.Experience working within an Agile team an advantageFluent in English.High levels of curiosity and autonomy.Experience or knowledge of any of the following an advantage; SAP Lumira,.Experience or knowledge of any of the following an advantage; SAP Lumira, SAP Business Intelligence Platform, SAP BW, SAP HANA, SAP UI5.Preparation of unit tests.Communicate proactively, precisely & accurately.Interact with colleagues in a highly international environment.Demonstrated problem solving and solution building skills as well as the initiative to deliver results..Preparation of unit tests.You value teamwork and have excellent collaboration skills.', null=True)),
                ('responsibilities', models.TextField(default="The responsibilities of a developer encompass a wide range of tasks throughout the software development lifecycle. Developers are primarily responsible for translating design specifications into functional and efficient code, often working collaboratively in a team. They need to possess a deep understanding of programming languages, frameworks, and development tools. Additionally, developers are tasked with debugging and troubleshooting issues, optimizing code for performance, and ensuring that the software meets quality standards through rigorous testing. Continuous learning is integral to staying updated with emerging technologies, enabling developers to adapt to evolving industry practices and contribute to the success of the projects they are involved in. Effective communication within the team and a commitment to delivering reliable and scalable solutions are crucial aspects of a developer's responsibilities.")),
                ('position', models.CharField(max_length=50)),
                ('salary', models.CharField(default='on your performance ', max_length=100)),
                ('apply_link', models.URLField()),
            ],
        ),
    ]
