# Generated by Django 4.1.7 on 2024-01-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_jobposting'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/jobposting'),
        ),
    ]
