# Generated by Django 4.1.7 on 2024-01-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_jobposting_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='intership',
            name='roale',
            field=models.TextField(blank=True, default='devloper', null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='salary',
            field=models.CharField(default='not disclosed', max_length=100),
        ),
    ]
