# Generated by Django 4.1.7 on 2024-01-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_intership_roale_alter_jobposting_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteinfo',
            name='aboutus_image',
            field=models.ImageField(default='job_logo.png', upload_to='static/img/'),
        ),
    ]
