# Generated by Django 4.1.7 on 2024-01-26 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_websiteinfo_aboutus_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='websiteinfo',
            old_name='aboutus_image',
            new_name='aboutus_logo',
        ),
    ]
